# Generated by Django 5.0.7 on 2024-08-04 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Apparels & Accessories'), (2, 'Automobiles'), (3, 'Beauty & Health'), (4, 'Books & Learning'), (5, 'Business & Industrial'), (6, 'Computers & Peripherals'), (7, 'Electronics, TVs & More'), (8, 'Events & Happenings'), (9, 'Fresh Veggies & Meat'), (10, 'Furnishings & Appliances'), (11, 'Jobs'), (12, 'Mobile Phone & Accessories'), (13, 'Music Instruments'), (14, 'Pets & Adoption & Free Stuff'), (15, 'Real Estate'), (16, 'Services'), (17, 'Sports & Fitness'), (18, 'Toys & Video Games'), (19, 'Travel, Tours & Packages')])),
                ('image', models.ImageField(upload_to='product/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
